In [1]:
import json
import requests
import pandas as pd
import numpy as np
from config_sk import api_key

In [2]:
#call nasdaq 100 company name list
nasdaq100_url=f"https://financialmodelingprep.com/api/v3/nasdaq_constituent?apikey={api_key}"
print(requests.get(nasdaq100_url))

<Response [200]>

In [3]:
nasdaq100_response = requests.get(nasdaq100_url).json()

In [23]:
#-------------------------------------------------------------------------------------------------------

In [4]:
#call latest stock news api
news_url=f"https://financialmodelingprep.com/api/v3/stock_news?limit=50&apikey={api_key}"
print(requests.get(news_url))

<Response [200]>

In [5]:
news_response = requests.get(news_url).json()

In [8]:
#-------------------------------------------------------------------------------------------------------

In [8]:
# collect a list of the Nasdaq100 constituents
nasdaq100_company_name = []
nasdaq100_company_symbol = []


for company in nasdaq100_response:
    nasdaq100_company_name.append(company['name'])
    nasdaq100_company_symbol.append(company['symbol'])

In [11]:
data1 = {'Company': nasdaq100_company_name, 
         'Symbol': nasdaq100_company_symbol,
        'News 1': ['' for i in range(len(nasdaq100_company_name))], 
        'News 2': ['' for i in range(len(nasdaq100_company_name))], 
        'News 3': ['' for i in range(len(nasdaq100_company_name))], 
        'News 4': ['' for i in range(len(nasdaq100_company_name))], 
        'News 5': ['' for i in range(len(nasdaq100_company_name))] 
       }
nasdaq100_df = pd.DataFrame(data=data1)
nasdaq100_df.head(-1)

                           Company Symbol News 1 News 2 News 3 News 4 News 5
0                     DocuSign Inc   DOCU
1    Zoom Video Communications Inc     ZM
2                       DexCom Inc   DXCM
3                       Splunk Inc   SPLK
4             Seattle Genetics Inc   SGEN
..                             ...    ...    ...    ...    ...    ...    ...
96                     Paychex Inc   PAYX
97                        KLA Corp   KLAC
98               Cisco Systems Inc   CSCO
99                    Autodesk Inc   ADSK
100                Match Group Inc   MTCH

[101 rows x 7 columns]

In [34]:
for index, row in nasdaq100_df.iterrows():
        
    symbol = row["Symbol"]
    date_url = f'https://financialmodelingprep.com/api/v3/ratios/{symbol}?period=quarter&limit=3&apikey={api_key}'
    response = requests.get(date_url).json()
    
    
    try:  
        
        snp_df.loc[index, "Q3 Date"] = response[0]["date"]
        snp_df.loc[index, "Q2 Date"] = response[1]["date"]
        snp_df.loc[index, "Q1 Date"] = response[2]["date"]
        
    except IndexError:
        print("Missing information")

Missing information
Missing information
Missing information

In [35]:
#get price 
for index, row in snp_df.iterrows():
    
    symbol = row["Symbol"]
    
    # Price Response for Q2 2020 Date
    date1 = row["Q3 Date"]
    date1_price_url = f'https://financialmodelingprep.com/api/v3/historical-price-full/{symbol}?from={date1}&to={date1}&apikey={api_key}'
    date1_response = requests.get(date1_price_url).json() 
    
    
    try:  
        snp_df.loc[index, "Q3 Price"] = date1_response['historical'][0]['close']
        
    except (IndexError, KeyError):
        print(f" - ")
    
    
    #Price Response for Q1 2020 Date
    date2 = row["Q2 Date"]
    date2_price_url = f'https://financialmodelingprep.com/api/v3/historical-price-full/{symbol}?from={date2}&to={date2}&apikey={api_key}'
    date2_response = requests.get(date2_price_url).json() 
    
    
    try:  
        snp_df.loc[index, "Q2 Price"] = date2_response['historical'][0]['close']
        
    except (IndexError, KeyError):
        print(f" - ")

            
    
    #Price Response for Q4 2019 Date
    date3 = row["Q1 Date"]
    date3_price_url = f'https://financialmodelingprep.com/api/v3/historical-price-full/{symbol}?from={date3}&to={date3}&apikey={api_key}'
    date3_response = requests.get(date3_price_url).json()
    
     
    try:  
        snp_df.loc[index, "Q1 Price"] = date3_response['historical'][0]['close']
    
    except (IndexError, KeyError):
        print(f" - ")

 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -
 -

In [37]:
snp_df.head(-1)

,Company,Symbol,Q3 Date,Q3 Price,Q2 Date,Q2 Price,Q1 Date,Q1 Price
0,Westinghouse Air Brake Technologies Corp,WAB,2020-06-30,57.4712,2020-03-31,47.9386,2019-12-31,77.3759
1,Take-Two Interactive Software Inc,TTWO,2020-06-30,139.57,2020-03-31,118.61,2019-12-31,122.43
2,Church & Dwight Co Inc,CHD,2020-06-30,77.1044,2020-03-31,63.8084,2019-12-31,70.325
3,Martin Marietta Materials Inc,MLM,2020-06-30,206.002,2020-03-31,188.184,2019-12-31,277.432
4,Edwards Lifesciences Corp,EW,2020-06-30,69.11,2020-03-31,62.8733,2019-12-31,77.7633
...,...,...,...,...,...,...,...,...
500,ETSY Inc,ETSY,2020-06-30,106.23,2020-03-31,38.44,2019-12-31,44.3
501,Tyler Technologies Inc,TYL,2020-06-30,346.88,2020-03-31,296.56,2019-12-31,300.02
502,Bio Rad Laboratories Inc,BIO,2020-06-30,451.49,2020-03-31,350.56,2019-12-31,370.03
503,West Pharmaceutical Services Inc,WST,2020-06-30,227.034,2020-03-31,152.016,2019-12-31,149.946
504,Domino's Pizza Inc,DPZ,2020-09-06,,2020-06-14,,2020-03-22,

In [36]:
snp_df.to_csv('../output/snp_historical_prices.csv')